#!/bin/env ruby

require 'json'
require '/opt/elasticbeanstalk/support/get_envvars'

env_vars = get_env_vars

leader_env_var = 'EB_IS_COMMAND_LEADER'

if ENV[leader_env_var]
    env_vars[leader_env_var] = ENV[leader_env_var]
end

staging_dir = `/opt/elasticbeanstalk/bin/get-config container -k app_staging_dir`

puts JSON.dump({
  'env' => env_vars.to_hash,
  'cwd' => staging_dir
})
